### ISSUE TITLE
lang support

### ISSUE THREAD

**Issue by KroeteTroete** [KroeteTroete/binmodder#3]
Make the program work with the multiline text that can be found in .lang files

**Comment by Trimatix** [comment]
I wonder if we could have this be a separate package so that other projects could re-use it?

**Comment by KroeteTroete** [comment]
That's a good idea ;)
I've been planning to do the same with the automatic string detection for bin files (bindetect.py). What do you think about me making a repo called "gofdetect" or something like that, placing bindetect.py and langdetect.py in there and then submoduling them into binmodder?

**Comment by KroeteTroete** [comment]
Issue has been moved to the new gofdetect repo

https://github.com/KroeteTroete/gofdetect/issues/1
